# Generated by Django 4.2.11 on 2026-01-29 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('analysis_type', models.CharField(choices=[('portfolio_performance', 'Portfolio Performance Analysis'), ('risk_assessment', 'Risk Assessment'), ('market_trends', 'Market Trends'), ('roi_forecast', 'ROI Forecast'), ('investment_allocation', 'Investment Allocation'), ('comparative_analysis', 'Comparative Analysis')], max_length=50)),
                ('description', models.TextField()),
                ('data', models.JSONField(help_text='JSON data containing analysis results')),
                ('investor_only', models.BooleanField(default=False, help_text='If True, this analysis is only visible to investors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dashboard Analysis',
                'verbose_name_plural': 'Dashboard Analyses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('investor', 'Investor'), ('user', 'Regular User'), ('admin', 'Administrator')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Portfolio',
                'verbose_name_plural': 'Investment Portfolios',
            },
        ),
    ]
