# Generated by Django 5.2.7 on 2025-10-27 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Startup name or pitch title', max_length=200)),
                ('sector', models.CharField(blank=True, help_text='Industry sector', max_length=100)),
                ('stage', models.CharField(blank=True, help_text='Funding stage (e.g., Seed, Series A)', max_length=50)),
                ('goal', models.CharField(blank=True, help_text='Funding goal (e.g., 500.000€)', max_length=64)),
                ('equity', models.IntegerField(blank=True, help_text='Equity percentage offered', null=True)),
                ('desc', models.TextField(blank=True, help_text='Pitch description')),
                ('img', models.URLField(blank=True, help_text='Image URL for pitch card')),
                ('valuation', models.CharField(blank=True, help_text='Calculated valuation', max_length=64)),
                ('is_public', models.BooleanField(default=True, help_text='Whether pitch is visible on marketplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created this pitch', on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pitch',
                'verbose_name_plural': 'Pitches',
                'ordering': ['-created_at'],
            },
        ),
    ]
