# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Investment amount in EUR', max_digits=12)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Equity percentage acquired', max_digits=5, null=True)),
                ('investment_date', models.DateTimeField(auto_now_add=True, help_text='Date of investment')),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('failed', 'Failed')], default='active', help_text='Current status of investment', max_length=20)),
                ('exit_date', models.DateTimeField(blank=True, help_text='Date of exit (if applicable)', null=True)),
                ('exit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Exit amount in EUR', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Investment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(help_text='User who made the investment', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(help_text='The pitch being invested in', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='api.pitch')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-investment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('investor', 'pitch'), name='unique_investor_pitch'),
        ),
    ]
