# Generated by Django 5.2.7 on 2025-11-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pitch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name', max_length=200)),
                ('topic', models.CharField(help_text='Event topic or panel description', max_length=200)),
                ('location', models.CharField(help_text='Location or platform (e.g., MS Teams, Zoom)', max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('date', models.DateTimeField(help_text='Event date and time')),
                ('link', models.URLField(blank=True, help_text='Meeting link or registration URL')),
                ('description', models.TextField(help_text='Detailed event description')),
                ('img', models.URLField(blank=True, help_text='Event cover image URL')),
                ('host', models.CharField(blank=True, help_text='Host name or organization', max_length=200)),
                ('is_public', models.BooleanField(default=True, help_text='Whether event is visible on marketplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
    ]
