# Generated by Django 5.2.7 on 2025-11-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='business_plan',
            field=models.FileField(blank=True, help_text='Business Plan PDF file', null=True, upload_to='business_plans/'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='financial_report',
            field=models.FileField(blank=True, help_text='Financial Report PDF file', null=True, upload_to='financial_reports/'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitch_deck',
            field=models.FileField(blank=True, help_text='Pitch Deck PDF file', null=True, upload_to='pitch_decks/'),
        ),
    ]
