# Generated by Django 5.2.7 on 2025-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pitch_business_plan_pitch_financial_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, help_text='Event cover image', null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='img',
            field=models.ImageField(blank=True, help_text='Pitch card image', null=True, upload_to='pitch_images/'),
        ),
    ]
