# Generated by Django 5.2.7 on 2025-12-02 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_img_alter_pitch_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When the pitch was saved')),
                ('pitch', models.ForeignKey(help_text='Pitch that was saved', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.pitch')),
                ('user', models.ForeignKey(help_text='User (investor) who saved this pitch', on_delete=django.db.models.deletion.CASCADE, related_name='saved_pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Pitch',
                'verbose_name_plural': 'Saved Pitches',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'pitch')},
            },
        ),
    ]
