# Generated by Django 5.2.7 on 2025-12-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_savedpitch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpitch',
            name='pitch',
            field=models.ForeignKey(help_text='The saved pitch', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='api.pitch'),
        ),
        migrations.AlterField(
            model_name='savedpitch',
            name='user',
            field=models.ForeignKey(help_text='User who saved this pitch', on_delete=django.db.models.deletion.CASCADE, related_name='saved_pitches', to=settings.AUTH_USER_MODEL),
        ),
    ]
