# Generated by Django 5.2.7 on 2025-12-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investment'),
        ('api', '0008_alter_savedpitch_pitch_alter_savedpitch_user'),
    ]

    operations = [
    ]
