"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Debug: Print if .env file was found
if env_path.exists():
    print(f"✅ .env file found at: {env_path}")
else:
    print(f"❌ .env file NOT found at: {env_path}")
print(f"EMAIL_HOST_USER from env: {os.environ.get('EMAIL_HOST_USER', 'NOT SET')}")
print(f"EMAIL_HOST_PASSWORD from env: {'SET' if os.environ.get('EMAIL_HOST_PASSWORD') else 'NOT SET'}")
print("="*50)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-axba)-tj+rcs(e&6(*p=50np8-*0_!6oxv(pbcq(nba_7lexwh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'corsheaders',
    'api',
    'users',
    'payments',
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Nuxt dev server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_ALL_ORIGINS = True


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# JWT Token Settings (Django Simple JWT)
SIMPLE_JWT = {
    # Token Lifetimes
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),        # Access Token gültig für 1 Stunde (statt 5 Min Standard)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),        # Refresh Token gültig für 7 Tage (statt 1 Tag Standard)
    
    # Token Rotation & Blacklisting
    'ROTATE_REFRESH_TOKENS': False,                     # Bei Token-Refresh wird KEIN neuer Refresh Token erstellt
    'BLACKLIST_AFTER_ROTATION': True,                   # Alte Tokens werden nach Rotation auf Blacklist gesetzt
    'UPDATE_LAST_LOGIN': True,                          # Aktualisiert last_login bei jedem Token-Refresh
    
    # Algorithm & Security
    'ALGORITHM': 'HS256',                               # Hash-Algorithmus für Token-Signatur
    'SIGNING_KEY': SECRET_KEY,                          # Verwendet Django SECRET_KEY zum Signieren
    'VERIFYING_KEY': None,                              # Für asymmetrische Algorithmen (RS256, etc.)
    
    # Token Headers
    'AUTH_HEADER_TYPES': ('Bearer',),                   # Authorization Header Format: "Bearer <token>"
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',           # Header-Name für Authorization
    
    # User Identification
    'USER_ID_FIELD': 'id',                              # User Model Field für user_id Claim
    'USER_ID_CLAIM': 'user_id',                         # JWT Claim Name für User ID
    
    # Token Types
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',                   # JWT Claim für Token Type
    
    # Sliding Tokens (optional - derzeit nicht verwendet)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# PayPal settings (set real credentials as environment variables in production)
PAYPAL_MODE = os.environ.get("PAYPAL_MODE", "sandbox")  # "live" for production
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID", "")
PAYPAL_CLIENT_SECRET = os.environ.get("PAYPAL_CLIENT_SECRET", "")
# If you use PayPal Webhook verification you'll need your webhook id
PAYPAL_WEBHOOK_ID = os.environ.get("PAYPAL_WEBHOOK_ID", "")

# Email settings
# Development: Console Backend (E-Mails im Terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production: SMTP Backend (echte E-Mails versenden)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True  # WICHTIG: Bei Port 465 muss SSL auf True sein
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  # Ihre Gmail-Adresse
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # App-Passwort
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@investify.com')  # Muss gleiche Adresse sein wie EMAIL_HOST_USER
EMAIL_TIMEOUT = 30  # Timeout in Sekunden

# Groq AI API Key
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')



