# Generated by Django 5.2.7 on 2026-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
